server:
  port: 8040
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

logging:
  level:
    com.netflix: debug
zuul:
  routes:
    user:
    path: user/**
    strip-prefix: false


